# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d66e4bbcc5cd6e58307fe91aa4cf809e657f0cdcbe2211375b687e9a2ded1d1b"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "f428e0d4f76832c3c4374a06823a39c932a934c151731458493c71fd0e47c9d2"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea55f02222bb0b299d213d98287f98b93e9073a61efe1bf64cdbaa56dbd93d74"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "9ebedf379d91f0737ffb7dfc2e9dce867b50492f3d7e9332b6482febd72da3a9"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-arm64.tar.gz"
    end
  end

  name "ai"
  desc "A small, fast CLI for talking to LLMs"
  homepage "https://github.com/tenxprotocols/ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai"]
    end
  end

  # No zap stanza required

end
