# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2991cf6b1573882446012fe57fc4350f706064e8287d13c8315fb9845108d18c"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "28612b12cde0f863535973b8dd12edf8a407083b42bd992a6f0c8e77921224a9"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95cee6a4b0d499aeff34746fb63e299a1745814921dce6d3dbe1199c12007bfd"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "643876bcca7d642bf9ee1b99a81a1324de4d7f2cb7874921d908fea6a06a0704"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-arm64.tar.gz"
    end
  end

  name "ai"
  desc "A small, fast CLI for talking to LLMs"
  homepage "https://github.com/tenxprotocols/ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai"

  # No zap stanza required

end
