# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "12af4855b005adee53780fb4fc91c1e155316a83549dba62e13dab4d7cb1a750"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "02d1c07b847459aefb0af9bc4f919b3346e006002b97b068105d9ad83ecf3847"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bbb164c3ed8a719b2654fcfbeb30b168bf688d989d8c807174f546dcba2926f0"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "4b0ed0e7cf70443a73a26e77af1cdd5da1c126f47462826f27adb5339bfd67e4"
      url "https://github.com/tenxprotocols/ai-cli/releases/download/v#{version}/ai-cli-#{version}-linux-arm64.tar.gz"
    end
  end

  name "ai"
  desc "A small, fast CLI for talking to LLMs"
  homepage "https://github.com/tenxprotocols/ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai"]
    end
  end

  # No zap stanza required

end
