# This file was generated by GoReleaser. DO NOT EDIT.
cask "nameit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f16fb41f82ce7be522b39b3c8ba7335b60861cf194441ee76909ed13e120dc43"
      url "https://github.com/tenxprotocols/nameit/releases/download/v#{version}/nameit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "749b3f28c4b7cd6c4be55745ce661b9ea833938ec48724d1c097953616b521b6"
      url "https://github.com/tenxprotocols/nameit/releases/download/v#{version}/nameit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53d3563b10627205c7b886a2e024326126faf62ba9ff8f0f16cea56ee8c59911"
      url "https://github.com/tenxprotocols/nameit/releases/download/v#{version}/nameit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6bdab78ec1f4bfb9a02bc906b26908538cfe4c8ed6401af1b127285959a409ea"
      url "https://github.com/tenxprotocols/nameit/releases/download/v#{version}/nameit_Linux_arm64.tar.gz"
    end
  end

  name "nameit"
  desc "Generate memorable random names in Heroku, modern, or animal styles"
  homepage "https://github.com/tenxprotocols/nameit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nameit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nameit"]
    end
  end

  # No zap stanza required

end
