# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCommitScribe < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/tenxprotocols/git-commit-scribe"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.0.0/git-commit-scribe-2.0.0-darwin-amd64.tar.gz"
      sha256 "2e0e45d3065f6092b68ca3125dc28bf86fb0e3e2952c444ae77e60bdaace76c1"

      def install
        bin.install "gscribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.0.0/git-commit-scribe-2.0.0-darwin-arm64.tar.gz"
      sha256 "4ba1c81b78b1e8e85f0a3c31d59c81f329ead04703dc75de342d85fc18ea96b8"

      def install
        bin.install "gscribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.0.0/git-commit-scribe-2.0.0-linux-amd64.tar.gz"
      sha256 "801d9778b669d6cb9528ac5f823544e9b86eec93cc28141715586541f305b629"
      def install
        bin.install "gscribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.0.0/git-commit-scribe-2.0.0-linux-arm64.tar.gz"
      sha256 "4f2f78a695229f0adf2d2c51ad380ccdaae45247de034bd47af868a80bab5c22"
      def install
        bin.install "gscribe"
      end
    end
  end

  test do
    system "#{bin}/gscribe", "--version"
  end
end
