# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gscribe < Formula
  desc "AI-powered git commit message generator"
  homepage "https://github.com/tenxprotocols/git-commit-scribe"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.1.0/git-commit-scribe-2.1.0-darwin-amd64.tar.gz"
      sha256 "8efb6c48a6d3cd38333e0623b1515a46930c2d5539ae6cd625cee17b6e385f98"

      define_method(:install) do
        bin.install "gscribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.1.0/git-commit-scribe-2.1.0-darwin-arm64.tar.gz"
      sha256 "178eb734d72d45945dec48ee4f2afc80433b74eedd8d88ffab3fb6073625dc86"

      define_method(:install) do
        bin.install "gscribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.1.0/git-commit-scribe-2.1.0-linux-amd64.tar.gz"
      sha256 "2ed36df76492a25fda3223f8edee949d65acab226e8a1e6fa3da2f947bd4821d"
      define_method(:install) do
        bin.install "gscribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tenxprotocols/git-commit-scribe/releases/download/v2.1.0/git-commit-scribe-2.1.0-linux-arm64.tar.gz"
      sha256 "746f32ed9e265c23c44a32c61510fbc9ed260d8b7072928162e4479e9bc3dba7"
      define_method(:install) do
        bin.install "gscribe"
      end
    end
  end

  test do
    system "#{bin}/gscribe", "--version"
  end
end
